package com.alexeyrand.swooshbot.telegram.enums;

public enum State {
    NO_WAITING,
    WAIT_FREE_PUBLISH,
    WAIT_PAID_PUBLISH,
    WAIT_SDEK_TARIFF,
    WAIT_SDEK_WEIGHT,
    WAIT_SDEK_DIMENSIONS,
    WAIT_SDEK_SENDER_FIO,
    WAIT_SDEK_SENDER_TELEPHONE,
    WAIT_SDEK_FIO,
    WAIT_SDEK_TELEPHONE,
    WAIT_SDEK_ITEM_DESCRIPTION,
    WAIT_SDEK_SHIPMENT_PVZ,
    WAIT_SDEK_DELIVERY_PVZ,
    WAIT_SDEK_PAYMENT,
    WAIT_SDEK,

    WAIT_EDIT_MAIN_MENU,

    WAIT_EDIT_PUBLISH_1,
    WAIT_EDIT_PUBLISH_2,
    WAIT_EDIT_PUBLISH_3,
    WAIT_EDIT_PUBLISH_4,

    WAIT_EDIT_CDEK_1,
    WAIT_EDIT_CDEK_2
}
