package com.alexeyrand.swooshbot.telegram.enums;

public enum State {
    NO_WAITING,
    WAIT_FREE_PUBLISH,
    WAIT_PAID_PUBLISH,
    WAIT_SDEK_TARIFF,
    WAIT_SDEK_WEIGHT,
    WAIT_SDEK_DIMENSIONS,
    WAIT_SDEK_FIO,
    WAIT_SDEK_TELEPHONE,
    WAIT_SDEK_ITEM_DESCRIPTION,
    WAIT_SDEK_SHIPMENT_PVZ,
    WAIT_SDEK_DELIVERY_PVZ,
    WAIT_SDEK,

}
