#spring.application.name=SwooshBot


bot:
  name: SwooshTemplateBot
  token: 6279864196:AAHrmKkP_jBzfRwgaZj_9Glk5ZQy2gVBTLU
  payments_token: 381764678:TEST:83885

spring:

  datasource:
    url: jdbc:h2:file:C:/data/Swoosh
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
#      port:
#        9090





answer:
  command:
    help: "Привет, я СВУШ бот! \n\nОт канала @swoosh\_market и чата @swoosh\_sell\n\nВ данном боте есть множество полезных услуг, выбери интересующую:"
    sdek: "Оформление накладных СДЕК, со скидкой до 50%\nВыгода для вас:\n1. Экономия Времени\nГотовая накладная позволяет не стоять в очереди. достаточно придти в пункт и передать посылку с написанным трек-номером работнику\n2. Экономия средств\nПри оформлении отправления через нашего бота, вы экономите до 50% процентов от изначальной стоимости\n3. Бесплатная упаковка\nВы можете попросить работника отделения упаковать вашу посылку в пакеты размера: А3, А4\n\nМы не несем никакой ответственности за посылки, а всего лишь предоставляем скидку на накладную\nС любыми вопросами по поводу посылок, рекомендуем вам обращаться напрямую в техническую поддержку СДЕК."
    sdekOrder: "Для формирования заказа укажите параметры посылки (размеры, вес и т.д.), адреса и другие данные. Далее, будет рассчитана стоимость доставки. После оплаты, вам будет отправлен трек номер."
    sdekOrder1: "Укажите номер тарифа:\n136 - Посылка \"Склад-Склад\" до 30 кг\n137 - Посылка \"Склад-Дверь\"до 30 кг"
    sdekOrder2: "Укажите вес посылки в граммах"
    sdekOrder3: "Укажите габариты посылки (ширину, длину, высоту) через пробел в см"
    publish: "Публикация постов в канале @swoosh\_market\n\n📮Виды постов:\n\nОбычная публикация - ваше объявление выкладывается в порядке очереди (максимум 3 вещи в одном посте)\n\nПубликация без очереди - платная услуга, ваше объявление выкладывается без очереди в ближайшее время (максимум 6 вещей в одном посте)\n\nТовар должен быть в наличии\nУслуги публикуем через рекламу\nСпам постами - бан."
    free: "Для публикации объявления отправьте сообщение с информацией о товарах\n\n*Объявление должно иметь вид:*\n1) Название товара\n2) Размер\n3) Город\n4) Состояние товара\n5) Цена\n6) Контакты для связи\n\nК сообщению прикрепите фотографии товаров (не более 9).\n\nТовар должен быть в наличии!\n\nВ одном объявлении указывать не более 3-х вещей. Ваше объявление выкладыватеся в порядке очереди."
    paid: "Для публикации объявления отправьте сообщение с информацией о товарах\n\n*Объявление должно иметь вид:*\n1) Название товара\n2) Размер\n3) Город\n4) Состояние товара\n5) Цена\n6) Контакты для связи\n\nК сообщению прикрепите фотографии товаров (не более 9).\n\nТовар должен быть в наличии!\n\nВ одном объявлении указывать не более 3-х вещей. Ваше объявление выкладывается вне очереди."
    check: "Для того, чтобы опубликовать объявление вне очереди, необходимо оплатить услугу по тарифу: 100 рублей за объявление. Одно объявление может содержать не более 3-х вещей. \n\nПосле успешной оплаты придет инструкция, как оформить сообщение с описанием товаров."