#spring.application.name=SwooshBot

bot:
  name: SwooshTemplateBot
  token: 6279864196:AAHrmKkP_jBzfRwgaZj_9Glk5ZQy2gVBTLU


answer:
  command:
    help: "Привет, я СВУШ бот! \n\nОт канала @swoosh\_market и чата @swoosh\_sell\n\nВ данном боте есть множество полезных услуг, выбери интересующую:"
    sdek: "Оформление накладных СДЕК, со скидкой до 50%\nВыгода для вас:\n1. Экономия Времени\nГотовая накладная позволяет не стоять в очереди. достаточно придти в пункт и передать посылку с написанным трек-номером работнику\n2. Экономия средств\nПри оформлении отправления через нашего бота, вы экономите до 50% процентов от изначальной стоимости\n3. Бесплатная упаковка\nВы можете попросить работника отделения упаковать вашу посылку в пакеты размера: А3, А4\n\nМы не несем никакой ответственности за посылки, а всего лишь предоставляем скидку на накладную\nС любыми вопросами по поводу посылок, рекомендуем вам обращаться напрямую в техническую поддержку СДЕК"
    publish: "Публикация постов в канале @swoosh\_market\n\n📮Виды постов:\n\nОбычная публикация - ваше объявление выкладывается в порядке очереди (максимум 3 вещи в одном посте)\n\nПубликация без очереди - платная услуга, ваше объявление выкладывается без очереди в ближайшее время (максимум 6 вещей в одном посте)\n\nТовар должен быть в наличии\nУслуги публикуем через рекламу\nСпам постами - бан"
    free1: "Отправьте только изображения (максимум 10)"